version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - HOSTNAME=hbr.test
    networks:
      - app-network

  mailtrap:
    image: eaudeweb/mailtrap
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
      - "2525:25"
    environment:
      - MT_USER=mailtrap
      - MT_PASSWD=mailtrap
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - .data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
      # - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    command: mysqld --sql_mode=""
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - /sessions
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
